inherit_from: .rubocop_todo.yml
Documentation:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - '**/Gemfile'
  Exclude:
    - db/schema.rb
