inherit_from: .rubocop_todo.yml 

require: rubocop-rspec

Documentation:
  Enabled: false

EndOfLine:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
